const state={items:[],trade:{yours:[],theirs:[]},inventory:[],listings:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>"$"+Math.round(Number(n)||0).toLocaleString();
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const key="ohioTradeLabV22";
const save=()=>localStorage.setItem(key,JSON.stringify({trade:state.trade,inventory:state.inventory,listings:state.listings}));
const getItem=id=>state.items.find(x=>x.id===id);
const getList=side=>side==="trade.yours"?state.trade.yours:side==="trade.theirs"?state.trade.theirs:state[side];
const total=list=>list.reduce((s,e)=>s+(getItem(e.id)?.value||0)*e.qty,0);
const avgDemand=list=>{let a=[];list.forEach(e=>{let d=getItem(e.id)?.demand;if(Number.isFinite(d))for(let i=0;i<e.qty;i++)a.push(d)});return a.length?a.reduce((x,y)=>x+y,0)/a.length:null};
const searchItems=q=>{q=q.trim().toLowerCase();if(!q)return[];return state.items.filter(x=>(x.name+" "+x.set+" "+x.weapon).toLowerCase().includes(q)).slice(0,12)};
function switchTab(id){$$(".page").forEach(x=>x.classList.toggle("active",x.id===id));$$("nav button").forEach(x=>x.classList.toggle("active",x.dataset.tab===id));location.hash=id;scrollTo(0,0)}
$$("nav button").forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
$$("[data-go]").forEach(b=>b.onclick=()=>switchTab(b.dataset.go));
function itemCard(x){return `<article class="item-card"><span class="pill">${esc(x.rarity)}</span><h3>${esc(x.name)}</h3><div class="money">${money(x.value)}</div><div class="muted">Demand ${x.demand??"?"}/10 • ${esc(x.set)}</div></article>`}
function renderHome(){let sets=new Set(state.items.map(x=>x.set));$("#statItems").textContent=state.items.length.toLocaleString();$("#statSets").textContent=sets.size;let top=[...state.items].sort((a,b)=>b.value-a.value);$("#statTop").textContent=money(top[0]?.value||0);$("#topItems").innerHTML=top.slice(0,8).map(itemCard).join("")}
function fillFilters(){let rar=[...new Set(state.items.map(x=>x.rarity))].sort(),sets=[...new Set(state.items.map(x=>x.set))].sort();$("#dbRarity").innerHTML='<option value="">All rarities</option>'+rar.map(x=>`<option>${esc(x)}</option>`).join("");$("#dbSet").innerHTML='<option value="">All sets</option>'+sets.map(x=>`<option>${esc(x)}</option>`).join("")}
function renderDB(){let q=$("#dbSearch").value.toLowerCase(),rar=$("#dbRarity").value,set=$("#dbSet").value,sort=$("#dbSort").value;let a=state.items.filter(x=>(!q||(x.name+" "+x.set+" "+x.weapon).toLowerCase().includes(q))&&(!rar||x.rarity===rar)&&(!set||x.set===set));a.sort(sort==="value-asc"?(x,y)=>x.value-y.value:sort==="demand-desc"?(x,y)=>(y.demand||0)-(x.demand||0):sort==="name"?(x,y)=>x.name.localeCompare(y.name):(x,y)=>y.value-x.value);$("#dbRows").innerHTML=a.slice(0,500).map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.set)}</td><td><span class="pill">${esc(x.rarity)}</span></td><td class="money">${money(x.value)}</td><td>${x.demand??"?"}/10</td><td>${esc(x.note||"")}</td></tr>`).join("");$("#dbCount").textContent=`Showing ${Math.min(a.length,500)} of ${a.length} matching items`;}
["dbSearch","dbRarity","dbSet","dbSort"].forEach(id=>$("#"+id).addEventListener("input",renderDB));
function setupPicker(inputId,resultId,side,after){let input=$("#"+inputId),box=$("#"+resultId);input.oninput=()=>{box.innerHTML=searchItems(input.value).map(x=>`<div class="result" data-id="${x.id}"><span><b>${esc(x.name)}</b><br><small class="muted">${esc(x.rarity)} • ${x.demand??"?"}/10</small></span><b>${money(x.value)}</b></div>`).join("");box.querySelectorAll(".result").forEach(r=>r.onclick=()=>{add(side,r.dataset.id);input.value="";box.innerHTML="";after()})};input.onblur=()=>setTimeout(()=>box.innerHTML="",180)}
function add(side,id){let a=getList(side),e=a.find(x=>x.id===id);e?e.qty++:a.push({id,qty:1});save()}
function alter(side,id,d){let a=getList(side),e=a.find(x=>x.id===id);if(!e)return;e.qty+=d;if(e.qty<=0){let next=a.filter(x=>x.id!==id);if(side==="inventory")state.inventory=next;else if(side==="trade.yours")state.trade.yours=next;else if(side==="trade.theirs")state.trade.theirs=next}save()}
function selectedHTML(side){let a=getList(side);if(!a.length)return'<div class="empty">No items added yet.</div>';return a.map(e=>{let x=getItem(e.id);return `<div class="selected"><div><b>${esc(x.name)}</b><div class="muted">${money(x.value)} each</div></div><div class="money">${money(x.value*e.qty)}</div><div class="qty"><button data-a="-1" data-id="${e.id}">−</button><b>${e.qty}</b><button data-a="1" data-id="${e.id}">+</button></div></div>`}).join("")}
function bindQty(container,side,render){container.querySelectorAll("[data-a]").forEach(b=>b.onclick=()=>{alter(side,b.dataset.id,Number(b.dataset.a));render()})}
function renderTrade(){let y=total(state.trade.yours),t=total(state.trade.theirs),diff=t-y;$("#yourTotal").textContent=money(y);$("#theirTotal").textContent=money(t);$("#yourItems").innerHTML=selectedHTML("trade.yours");$("#theirItems").innerHTML=selectedHTML("trade.theirs");bindTradeQty($("#yourItems"),"yours");bindTradeQty($("#theirItems"),"theirs");let v=$("#tradeVerdict"),pct=Math.max(y,t)?Math.abs(diff)/Math.max(y,t):0;if(!y&&!t){v.className="verdict";v.innerHTML="<h2>Build both sides</h2><div class='muted'>Add items to compare the trade.</div>"}else if(pct<=.05){v.className="verdict fair";v.innerHTML=`<h2>Fair trade</h2><div>Difference: <b>${money(Math.abs(diff))}</b> (${(pct*100).toFixed(1)}%)</div>`}else if(diff>0){v.className="verdict good";v.innerHTML=`<h2>You are gaining value</h2><div>Their side is worth <b>${money(diff)}</b> more.</div>`}else{v.className="verdict bad";v.innerHTML=`<h2>You are losing value</h2><div>Your side is worth <b>${money(-diff)}</b> more.</div>`}renderSuggestions(diff)}
function bindTradeQty(c,side){c.querySelectorAll("[data-a]").forEach(b=>b.onclick=()=>{let e=state.trade[side].find(x=>x.id===b.dataset.id);e.qty+=Number(b.dataset.a);if(e.qty<=0)state.trade[side]=state.trade[side].filter(x=>x.id!==b.dataset.id);save();renderTrade()})}
function renderSuggestions(diff){let need=Math.abs(diff);if(need===0){$("#tradeSuggestions").innerHTML='<span class="muted">No value gap to match.</span>';return}let used=new Set([...state.trade.yours,...state.trade.theirs].map(x=>x.id));let a=state.items.filter(x=>!used.has(x.id)&&x.value<=need*1.35&&x.value>=need*.35).sort((x,y)=>Math.abs(x.value-need)-Math.abs(y.value-need)||((y.demand||0)-(x.demand||0))).slice(0,8);$("#tradeSuggestions").innerHTML=a.length?a.map(x=>`<button class="suggestion" data-id="${x.id}">${esc(x.name)} • ${money(x.value)}</button>`).join(""):'<span class="muted">No close single-item match. Try a combination of smaller items.</span>';$("#tradeSuggestions").querySelectorAll("button").forEach(b=>b.onclick=()=>{add("trade.yours",b.dataset.id);renderTrade()})}
setupPicker("yourSearch","yourResults","trade.yours",renderTrade);setupPicker("theirSearch","theirResults","trade.theirs",renderTrade);
$("#clearTrade").onclick=()=>{if(confirm("Clear both sides of the trade?")){state.trade={yours:[],theirs:[]};save();renderTrade()}};
function renderInventory(){let a=state.inventory,val=total(a),dem=avgDemand(a),top=[...a].sort((p,q)=>(getItem(q.id)?.value||0)-(getItem(p.id)?.value||0))[0];$("#inventoryValue").textContent=money(val);$("#inventoryCount").textContent=a.reduce((s,e)=>s+e.qty,0);$("#inventoryDemand").textContent=dem==null?"—":dem.toFixed(1)+"/10";$("#inventoryTop").textContent=top?getItem(top.id).name:"—";$("#inventoryItems").innerHTML=selectedHTML("inventory");bindQty($("#inventoryItems"),"inventory",renderInventory);analysisBars("rarityAnalysis","rarity");analysisBars("setAnalysis","set")}
function analysisBars(id,field){let map={};state.inventory.forEach(e=>{let x=getItem(e.id);map[x[field]]=(map[x[field]]||0)+x.value*e.qty});let rows=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,7),max=rows[0]?.[1]||1;$("#"+id).innerHTML=rows.length?rows.map(([k,v])=>`<div class="bar-row"><span>${esc(k)}</span><div class="bar"><i style="width:${v/max*100}%"></i></div><b>${money(v)}</b></div>`).join(""):'<div class="empty">Add inventory items to see analysis.</div>'}
setupPicker("inventorySearch","inventoryResults","inventory",renderInventory);
$("#clearInventory").onclick=()=>{if(confirm("Clear your saved inventory?")){state.inventory=[];save();renderInventory()}};
$("#exportInventory").onclick=()=>{let b=new Blob([JSON.stringify({version:1,inventory:state.inventory},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="ohio-trade-lab-inventory.json";a.click();URL.revokeObjectURL(a.href)};
$("#importInventory").onchange=async e=>{try{let j=JSON.parse(await e.target.files[0].text());if(!Array.isArray(j.inventory))throw Error();state.inventory=j.inventory.filter(e=>getItem(e.id)&&e.qty>0);save();renderInventory()}catch{alert("That inventory file could not be imported.")}};
function renderListings(){let q=$("#listingSearch").value.toLowerCase(),a=state.listings.filter(x=>(x.user+" "+x.offer+" "+x.want+" "+x.notes).toLowerCase().includes(q));$("#listings").innerHTML=a.length?a.map(x=>`<article class="listing"><div class="listing-meta"><b>@${esc(x.user)}</b><span>${new Date(x.time).toLocaleString()}</span></div><h3>Offering: ${esc(x.offer)}</h3><p><b>Looking for:</b> ${esc(x.want)}</p>${x.notes?`<p class="muted">${esc(x.notes)}</p>`:""}<div class="listing-actions"><button class="danger" data-delete="${x.id}">Delete</button></div></article>`).join(""):'<div class="empty">No matching trade listings.</div>';$("#listings").querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>{state.listings=state.listings.filter(x=>x.id!==b.dataset.delete);save();renderListings()})}
$("#listingForm").onsubmit=e=>{e.preventDefault();state.listings.unshift({id:crypto.randomUUID(),user:$("#listingUser").value.trim(),offer:$("#listingOffer").value.trim(),want:$("#listingWant").value.trim(),notes:$("#listingNotes").value.trim(),time:Date.now()});save();e.target.reset();renderListings()};
$("#listingSearch").oninput=renderListings;
async function start(){let data=await fetch("data/items.json").then(r=>r.json());state.items=data.items;try{let old=JSON.parse(localStorage.getItem(key)||"{}");state.trade=old.trade||state.trade;state.inventory=old.inventory||[];state.listings=old.listings||[]}catch{}renderHome();fillFilters();renderDB();renderTrade();renderInventory();renderListings();switchTab((location.hash||"#home").slice(1))}
start().catch(e=>{document.body.innerHTML="<main><h1>Could not load the value database.</h1><p>"+esc(e.message)+"</p></main>"});
